/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NOTIFICACIONES_H_RPCGEN
#define _NOTIFICACIONES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define gestion_notificaciones 0x20000002
#define gestion_notificaiones_version 2

#if defined(__STDC__) || defined(__cplusplus)
#define enviarNotificacion 1
extern  bool_t * enviarnotificacion_2(char **, CLIENT *);
extern  bool_t * enviarnotificacion_2_svc(char **, struct svc_req *);
extern int gestion_notificaciones_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define enviarNotificacion 1
extern  bool_t * enviarnotificacion_2();
extern  bool_t * enviarnotificacion_2_svc();
extern int gestion_notificaciones_2_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NOTIFICACIONES_H_RPCGEN */
